### PR TITLE
Organize to configs

### PR DESCRIPTION
**Pull request by hadi7546**
I collected all the configurations that the guys had added in the previous pull requests in one pull request. And for easier use, I collected them in one text.

### CODE REVIEW

**Comment by 0xland** [comment]
Thanks for your kindness.
Unfortunately IOS links are not correct. So I can't merge your PR.

**Comment by 0xland** [comment]
You can use this python code to generate IOS links:
https://github.com/WeAreMahsaAmini/FreeInternet/blob/main/guides/shadowsocks-v2ray-tls/ss-link-generator.py

**Comment by hadi7546** [comment]
> You can use this python code to generate IOS links:
> https://github.com/WeAreMahsaAmini/FreeInternet/blob/main/guides/shadowsocks-v2ray-tls/ss-link-generator.py

What should I give it as input?

**Comment by grimpenmire** [comment]
I think someone on another issue mentioned that the Android link also works for iOS clients. If others can also confirm this, we could just get rid of the extra fluff, and have one clean list.

**Comment by 0xland** [comment]
> I think someone on another issue mentioned that the Android link also works for iOS clients. If others can also confirm this, we could just get rid of the extra fluff, and have one clean list.

works sometimes, not all the time

**Comment by grimpenmire** [comment]
Does that mean the links can sometimes be added and sometimes not? Or that they work in some apps and not in others? Or that adding them works fine, but the vpn itself doesn't always work?

**Comment by 0xland** [comment]
> Does that mean the links can sometimes be added and sometimes not? Or that they work in some apps and not in others? Or that adding them works fine, but the vpn itself doesn't always work?

iOS client can't parse android url params,so if android url imported to iOS client which uses default params,it will work, but not with non default params

**Pull request closed without merging**
